[package]
name = "sudoku-z3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
z3 = "0.12.1"
serde_json = "1.0"
clap = { version = "4.4.10", features = ["derive"] }
